apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-java-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-java-demo
  template:
    metadata:
      labels:
        app: k8s-java-demo
    spec:
      containers:
      - name: k8s-java-demo
        image: registry.cn-hangzhou.aliyuncs.com/haoshuwei/java-demo:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-java-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: k8s-java-demo
  selector:
    app: k8s-java-demo
  type: LoadBalancer
