apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mini-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-app
  template:
    metadata:
      labels:
        app: mini-app
    spec:
      containers:
      - name: mini-app
        image: registry.cn-beijing.aliyuncs.com/mini-app/devops:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mini-app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: mini-app
  selector:
    app: mini-app
  type: LoadBalancer
